// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BSK8neW98uBXSWICFGHh-iew88qcF_Q',
    appId: '1:563370810778:web:6c0a8ca4402de42880ae23',
    messagingSenderId: '563370810778',
    projectId: 'product-distribution-ec068',
    authDomain: 'product-distribution-ec068.firebaseapp.com',
    storageBucket: 'product-distribution-ec068.appspot.com',
    measurementId: 'G-H6ML53S1W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgMZXvxn-TOfTzKXI6ixp_1DMzt3EK6Y',
    appId: '1:563370810778:android:0e4f0728b637db3380ae23',
    messagingSenderId: '563370810778',
    projectId: 'product-distribution-ec068',
    storageBucket: 'product-distribution-ec068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBowkO9dj1IWzwzoAuAg3YeoZfj8syBFM',
    appId: '1:563370810778:ios:dbc8394a4963f9b080ae23',
    messagingSenderId: '563370810778',
    projectId: 'product-distribution-ec068',
    storageBucket: 'product-distribution-ec068.appspot.com',
    iosClientId: '563370810778-idm1ao921nesjlsrqr7uura5la72dr6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBowkO9dj1IWzwzoAuAg3YeoZfj8syBFM',
    appId: '1:563370810778:ios:dbc8394a4963f9b080ae23',
    messagingSenderId: '563370810778',
    projectId: 'product-distribution-ec068',
    storageBucket: 'product-distribution-ec068.appspot.com',
    iosClientId: '563370810778-idm1ao921nesjlsrqr7uura5la72dr6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdProject',
  );
}
